name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./scripts/process-covid-vaccinations.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data
          downloaded_filename: data/vaccination.json
          postprocess: ./scripts/process-covid-vaccinations.js
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://data.cdc.gov/resource/9mfq-cb36.json?state=MO
          downloaded_filename: data/cases_mo.json
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://data.cdc.gov/resource/9mfq-cb36.json?state=IL
          downloaded_filename: data/cases_il.json
